"""fix bugs

Revision ID: a59369522ca4
Revises: f074be30ff6a
Create Date: 2025-04-30 20:58:19.262884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a59369522ca4'
down_revision: Union[str, None] = 'f074be30ff6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_users', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.alter_column('web_users', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_unique_constraint(None, 'web_users', ['phone_number'])
    op.create_unique_constraint(None, 'web_users', ['username'])
    op.create_unique_constraint(None, 'web_users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_users', type_='unique')
    op.drop_constraint(None, 'web_users', type_='unique')
    op.drop_constraint(None, 'web_users', type_='unique')
    op.alter_column('web_users', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('web_users', 'password',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###
