"""fix v5

Revision ID: b94b9993fbb5
Revises: c8cbe72b8d38
Create Date: 2025-05-02 01:01:51.914758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94b9993fbb5'
down_revision: Union[str, None] = 'c8cbe72b8d38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_users_currency_subscribes_fkey', 'telegram_users', type_='foreignkey')
    op.drop_constraint('telegram_users_crypto_subscribes_fkey', 'telegram_users', type_='foreignkey')
    op.drop_column('telegram_users', 'crypto_subscribes')
    op.drop_column('telegram_users', 'currency_subscribes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('currency_subscribes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('telegram_users', sa.Column('crypto_subscribes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('telegram_users_crypto_subscribes_fkey', 'telegram_users', 'crypto_subscribes', ['crypto_subscribes'], ['id'])
    op.create_foreign_key('telegram_users_currency_subscribes_fkey', 'telegram_users', 'currency_subscribes', ['currency_subscribes'], ['id'])
    # ### end Alembic commands ###
