"""Fix bugs again

Revision ID: c8cbe72b8d38
Revises: 718c4492894f
Create Date: 2025-05-01 20:26:19.891454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8cbe72b8d38'
down_revision: Union[str, None] = '718c4492894f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('crypto_subscribes', sa.Integer(), nullable=True))
    op.add_column('telegram_users', sa.Column('currency_subscribes', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_users', 'crypto_subscribes', ['crypto_subscribes'], ['id'])
    op.create_foreign_key(None, 'telegram_users', 'currency_subscribes', ['currency_subscribes'], ['id'])
    op.drop_constraint('web_users_currency_subscribes_fkey', 'web_users', type_='foreignkey')
    op.drop_constraint('web_users_crypto_subscribes_fkey', 'web_users', type_='foreignkey')
    op.drop_column('web_users', 'currency_subscribes')
    op.drop_column('web_users', 'crypto_subscribes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('web_users', sa.Column('crypto_subscribes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('web_users', sa.Column('currency_subscribes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('web_users_crypto_subscribes_fkey', 'web_users', 'crypto_subscribes', ['crypto_subscribes'], ['id'])
    op.create_foreign_key('web_users_currency_subscribes_fkey', 'web_users', 'currency_subscribes', ['currency_subscribes'], ['id'])
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.drop_column('telegram_users', 'currency_subscribes')
    op.drop_column('telegram_users', 'crypto_subscribes')
    # ### end Alembic commands ###
