"""fix bugs v2

Revision ID: d518f9778c9c
Revises: a59369522ca4
Create Date: 2025-04-30 21:02:47.697734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd518f9778c9c'
down_revision: Union[str, None] = 'a59369522ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_users', 'crypto_subscribes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('web_users', 'currency_subscribes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('web_users', 'currency_subscribes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('web_users', 'crypto_subscribes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
