"""Upgrade db 2

Revision ID: f074be30ff6a
Revises: b2b3b74c866f
Create Date: 2025-04-28 21:03:24.703888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f074be30ff6a'
down_revision: Union[str, None] = 'b2b3b74c866f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_subscribes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('symbol1', sa.String(length=50), nullable=False),
    sa.Column('symbol2', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['crypto.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_subscribes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('symbol1', sa.String(length=50), nullable=False),
    sa.Column('symbol2', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['web_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('telegram_users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'telegram_users', 'web_users', ['user_id'], ['id'])
    op.add_column('web_users', sa.Column('crypto_subscribes', sa.Integer(), nullable=False))
    op.add_column('web_users', sa.Column('currency_subscribes', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'web_users', 'currency_subscribes', ['currency_subscribes'], ['id'])
    op.create_foreign_key(None, 'web_users', 'crypto_subscribes', ['crypto_subscribes'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'web_users', type_='foreignkey')
    op.drop_constraint(None, 'web_users', type_='foreignkey')
    op.drop_column('web_users', 'currency_subscribes')
    op.drop_column('web_users', 'crypto_subscribes')
    op.drop_constraint(None, 'telegram_users', type_='foreignkey')
    op.drop_column('telegram_users', 'user_id')
    op.drop_table('currency_subscribes')
    op.drop_table('crypto_subscribes')
    # ### end Alembic commands ###
